In [1]:
import pandas as pd

from PATHS import DATA_FOLDER
from data_prep import merge_open_close
from info_extraction import calc_profit

In [2]:
# J = jump trailing
# S = simple trailing
# N = adt-atr filter NOT used
# L,G = adt-atr filter used and atr <, > parameter amount


open_df = pd.read_csv(DATA_FOLDER + 'M15/2024-2026/smaller_spike/simple_trailing/open_trades_test.csv',sep=';')
close_df = pd.read_csv(DATA_FOLDER + 'M15/2024-2026/smaller_spike/simple_trailing/closed_trades_test.csv',sep=';')
S_N_merge_df = merge_open_close(open_df,close_df)

open_df = pd.read_csv(DATA_FOLDER + 'M15/2024-2026/smaller_spike/simple_trailing/ADX_ATR_FILTER/ATR_FILTER_GREATERTHAN_VALUE/open_trades_test.csv',sep=';')
close_df = pd.read_csv(DATA_FOLDER + 'M15/2024-2026/smaller_spike/simple_trailing/ADX_ATR_FILTER/ATR_FILTER_GREATERTHAN_VALUE/closed_trades_test.csv',sep=';')
S_G_merge_df = merge_open_close(open_df,close_df)

open_df = pd.read_csv(DATA_FOLDER + 'M15/2024-2026/smaller_spike/simple_trailing/ADX_ATR_FILTER/ATR_FILTER_LESSTHAN_VALUE/open_trades_test.csv',sep=';')
close_df = pd.read_csv(DATA_FOLDER + 'M15/2024-2026/smaller_spike/simple_trailing/ADX_ATR_FILTER/ATR_FILTER_LESSTHAN_VALUE/closed_trades_test.csv',sep=';')
S_L_merge_df = merge_open_close(open_df,close_df)

open_df = pd.read_csv(DATA_FOLDER + 'M15/2024-2026/smaller_spike/jump_trailing/open_trades_test.csv',sep=';')
close_df = pd.read_csv(DATA_FOLDER + 'M15/2024-2026/smaller_spike/jump_trailing/closed_trades_test.csv',sep=';')
J_N_merge_df = merge_open_close(open_df,close_df)

open_df = pd.read_csv(DATA_FOLDER + 'M15/2024-2026/smaller_spike/jump_trailing/ADX_ATR_FILTER/ATR_FILTER_GREATERTHAN_VALUE/open_trades_test.csv',sep=';')
close_df = pd.read_csv(DATA_FOLDER + 'M15/2024-2026/smaller_spike/jump_trailing/ADX_ATR_FILTER/ATR_FILTER_GREATERTHAN_VALUE/closed_trades_test.csv',sep=';')
J_G_merge_df = merge_open_close(open_df,close_df)

open_df = pd.read_csv(DATA_FOLDER + 'M15/2024-2026/smaller_spike/jump_trailing/ADX_ATR_FILTER/ATR_FILTER_LESSTHAN_VALUE/open_trades_test.csv',sep=';')
close_df = pd.read_csv(DATA_FOLDER + 'M15/2024-2026/smaller_spike/jump_trailing/ADX_ATR_FILTER/ATR_FILTER_LESSTHAN_VALUE/closed_trades_test.csv',sep=';')
J_L_merge_df = merge_open_close(open_df,close_df)

df_dict = {
    'SimpleTrailing_NoFilter_None':[S_N_merge_df],
    'SimpleTrailing_Filter_Greater':[S_G_merge_df],
    'SimpleTrailing_Filter_Less':[S_L_merge_df],
    'JumpTrailing_NoFilter_None':[J_N_merge_df],
    'JumpTrailing_Filter_Greater':[J_G_merge_df],
    'JumpTrailing_Filter_Less':[J_L_merge_df]
    }

for key in df_dict:
    profit_df = calc_profit(df_dict[key][0],len(df_dict[key][0]))
    profit_df['Profit_With_Drawdown'] = profit_df['Profit'] * (30 / profit_df['Max_Drawdown_Pct'])
    df_dict[key].append(profit_df)

'''for key in df_dict:
    temp_df = df_dict[key][0]
    Mask = (
        (temp_df["slow_MA"] > 0.0)
        &
        (
            (temp_df["SAR"] <= 0.0)
            |
            (temp_df["fast_MA_prev"] > 0.0)
        )
    )
    df_dict[key].append(calc_profit(temp_df,
                                    len(temp_df),
                                    MASK))
    '''

'for key in df_dict:\n    temp_df = df_dict[key][0]\n    Mask = (\n        (temp_df["slow_MA"] > 0.0)\n        &\n        (\n            (temp_df["SAR"] <= 0.0)\n            |\n            (temp_df["fast_MA_prev"] > 0.0)\n        )\n    )\n    df_dict[key].append(calc_profit(temp_df,\n                                    len(temp_df),\n                                    MASK))\n    '

In [3]:
df = df_dict['SimpleTrailing_NoFilter_None'][0]
df[df['Test_ID'] == '0.025_1.0_0.030_4.0']['Profit']

82273     62.266167
82274     42.025208
82275    168.567775
82276     -0.780000
82277     68.860000
            ...
82415    -10.705050
82416      0.840000
82417     62.659479
82418     29.750000
82419     -1.000000
Name: Profit, Length: 147, dtype: float64

In [4]:
['SimpleTrailing_NoFilter_None',
 'SimpleTrailing_Filter_Greater',
 'SimpleTrailing_Filter_Less',
 'JumpTrailing_NoFilter_None',
 'JumpTrailing_Filter_Greater',
 'JumpTrailing_Filter_Less'
    ]

['SimpleTrailing_NoFilter_None',
 'SimpleTrailing_Filter_Greater',
 'SimpleTrailing_Filter_Less',
 'JumpTrailing_NoFilter_None',
 'JumpTrailing_Filter_Greater',
 'JumpTrailing_Filter_Less']

In [5]:
df_dict['SimpleTrailing_NoFilter_None'][1][['Test_ID', 'Type', 'Profit','Profit_With_Drawdown', 'Max_Drawdown', 'Max_Drawdown_Pct',
       'Trade_Count', 'Winning_Profit', 'Winning_Count', 'Losing_Profit',
       'Losing_Count']].sort_values(by='Profit_With_Drawdown',ascending=False).head(20)

,Test_ID,Type,Profit,Profit_With_Drawdown,Max_Drawdown,Max_Drawdown_Pct,Trade_Count,Winning_Profit,Winning_Count,Losing_Profit,Losing_Count
95,0.025_1.0_0.030_4.0,Long,1145.293060,3573.387533,1096.733585,9.615188,146,5904.528569,54,-4759.235509,92
94,0.025_1.0_0.030_3.0,Long,1145.293060,3573.387533,1096.733585,9.615188,146,5904.528569,54,-4759.235509,92
93,0.025_1.0_0.030_2.0,Long,1145.293060,3573.387533,1096.733585,9.615188,146,5904.528569,54,-4759.235509,92
92,0.025_1.0_0.030_1.0,Long,1145.293060,3573.387533,1096.733585,9.615188,146,5904.528569,54,-4759.235509,92
71,0.020_1.0_0.030_4.0,Long,1085.653662,3010.805546,1239.159435,10.817573,272,10309.844304,110,-9224.190642,162
70,0.020_1.0_0.030_3.0,Long,1085.653662,3010.805546,1239.159435,10.817573,272,10309.844304,110,-9224.190642,162
69,0.020_1.0_0.030_2.0,Long,1085.653662,3010.805546,1239.159435,10.817573,272,10309.844304,110,-9224.190642,162
68,0.020_1.0_0.030_1.0,Long,1085.653662,3010.805546,1239.159435,10.817573,272,10309.844304,110,-9224.190642,162
116,0.030_1.0_0.030_1.0,Long,498.154134,2892.207643,569.574020,5.167203,83,3087.952027,33,-2589.797894,50
117,0.030_1.0_0.030_2.0,Long,498.154134,2892.207643,569.574020,5.167203,83,3087.952027,33,-2589.797894,50
118,0.030_1.0_0.030_3.0,Long,498.154134,2892.207643,569.574020,5.167203,83,3087.952027,33,-2589.797894,50
119,0.030_1.0_0.030_4.0,Long,498.154134,2892.207643,569.574020,5.167203,83,3087.952027,33,-2589.797894,50
112,0.030_1.0_0.025_1.0,Long,258.284635,1523.577406,532.331045,5.085753,86,2496.824745,31,-2238.540110,55
113,0.030_1.0_0.025_2.0,Long,258.284635,1523.577406,532.331045,5.085753,86,2496.824745,31,-2238.540110,55
114,0.030_1.0_0.025_3.0,Long,258.284635,1523.577406,532.331045,5.085753,86,2496.824745,31,-2238.540110,55
115,0.030_1.0_0.025_4.0,Long,258.284635,1523.577406,532.331045,5.085753,86,2496.824745,31,-2238.540110,55
67,0.020_1.0_0.025_4.0,Long,511.782350,1348.052458,1251.975401,11.389372,300,8665.021351,120,-8153.239000,179
66,0.020_1.0_0.025_3.0,Long,511.782350,1348.052458,1251.975401,11.389372,300,8665.021351,120,-8153.239000,179
65,0.020_1.0_0.025_2.0,Long,511.782350,1348.052458,1251.975401,11.389372,300,8665.021351,120,-8153.239000,179
64,0.020_1.0_0.025_1.0,Long,511.782350,1348.052458,1251.975401,11.389372,300,8665.021351,120,-8153.239000,179

In [6]:
df_dict['SimpleTrailing_Filter_Greater'][1][['Test_ID', 'Type', 'Profit','Profit_With_Drawdown', 'Max_Drawdown', 'Max_Drawdown_Pct',
       'Trade_Count', 'Winning_Profit', 'Winning_Count', 'Losing_Profit',
       'Losing_Count']].sort_values(by='Profit_With_Drawdown',ascending=False).head(20)

,Test_ID,Type,Profit,Profit_With_Drawdown,Max_Drawdown,Max_Drawdown_Pct,Trade_Count,Winning_Profit,Winning_Count,Losing_Profit,Losing_Count
112,0.030_1.0_0.025_1.0,Long,3.234796,16.660581,600.443790,5.824760,50,1330.544317,18,-1327.309521,32
113,0.030_1.0_0.025_2.0,Long,3.234796,16.660581,600.443790,5.824760,50,1330.544317,18,-1327.309521,32
114,0.030_1.0_0.025_3.0,Long,3.234796,16.660581,600.443790,5.824760,50,1330.544317,18,-1327.309521,32
115,0.030_1.0_0.025_4.0,Long,3.234796,16.660581,600.443790,5.824760,50,1330.544317,18,-1327.309521,32
92,0.025_1.0_0.030_1.0,Long,-64.126730,-221.647033,927.251209,8.679574,81,2634.138070,27,-2698.264800,54
93,0.025_1.0_0.030_2.0,Long,-64.126730,-221.647033,927.251209,8.679574,81,2634.138070,27,-2698.264800,54
94,0.025_1.0_0.030_3.0,Long,-64.126730,-221.647033,927.251209,8.679574,81,2634.138070,27,-2698.264800,54
95,0.025_1.0_0.030_4.0,Long,-64.126730,-221.647033,927.251209,8.679574,81,2634.138070,27,-2698.264800,54
111,0.030_1.0_0.020_4.0,Long,-52.254869,-256.360044,630.187535,6.115017,53,1182.558032,18,-1234.812901,35
110,0.030_1.0_0.020_3.0,Long,-52.254869,-256.360044,630.187535,6.115017,53,1182.558032,18,-1234.812901,35
109,0.030_1.0_0.020_2.0,Long,-52.254869,-256.360044,630.187535,6.115017,53,1182.558032,18,-1234.812901,35
108,0.030_1.0_0.020_1.0,Long,-52.254869,-256.360044,630.187535,6.115017,53,1182.558032,18,-1234.812901,35
119,0.030_1.0_0.030_4.0,Long,-68.320170,-298.609656,715.283204,6.863827,48,1531.894799,17,-1600.214969,31
118,0.030_1.0_0.030_3.0,Long,-68.320170,-298.609656,715.283204,6.863827,48,1531.894799,17,-1600.214969,31
117,0.030_1.0_0.030_2.0,Long,-68.320170,-298.609656,715.283204,6.863827,48,1531.894799,17,-1600.214969,31
116,0.030_1.0_0.030_1.0,Long,-68.320170,-298.609656,715.283204,6.863827,48,1531.894799,17,-1600.214969,31
71,0.020_1.0_0.030_4.0,Long,-225.138293,-607.337666,1219.660200,11.120912,134,4106.768700,50,-4331.906992,84
70,0.020_1.0_0.030_3.0,Long,-225.138293,-607.337666,1219.660200,11.120912,134,4106.768700,50,-4331.906992,84
69,0.020_1.0_0.030_2.0,Long,-225.138293,-607.337666,1219.660200,11.120912,134,4106.768700,50,-4331.906992,84
68,0.020_1.0_0.030_1.0,Long,-225.138293,-607.337666,1219.660200,11.120912,134,4106.768700,50,-4331.906992,84

In [7]:
df_dict['SimpleTrailing_Filter_Less'][1][['Test_ID', 'Type', 'Profit','Profit_With_Drawdown', 'Max_Drawdown', 'Max_Drawdown_Pct',
       'Trade_Count', 'Winning_Profit', 'Winning_Count', 'Losing_Profit',
       'Losing_Count']].sort_values(by='Profit_With_Drawdown',ascending=False).head(20)

,Test_ID,Type,Profit,Profit_With_Drawdown,Max_Drawdown,Max_Drawdown_Pct,Trade_Count,Winning_Profit,Winning_Count,Losing_Profit,Losing_Count
64,0.020_1.0_0.025_1.0,Long,1665.268483,17287.619524,344.660422,2.889817,89,4006.896897,43,-2341.628413,46
65,0.020_1.0_0.025_2.0,Long,1665.268483,17287.619524,344.660422,2.889817,89,4006.896897,43,-2341.628413,46
66,0.020_1.0_0.025_3.0,Long,1665.268483,17287.619524,344.660422,2.889817,89,4006.896897,43,-2341.628413,46
67,0.020_1.0_0.025_4.0,Long,1665.268483,17287.619524,344.660422,2.889817,89,4006.896897,43,-2341.628413,46
68,0.020_1.0_0.030_1.0,Long,1866.889872,12429.478680,557.771288,4.505957,88,4660.265193,45,-2793.375321,43
69,0.020_1.0_0.030_2.0,Long,1866.889872,12429.478680,557.771288,4.505957,88,4660.265193,45,-2793.375321,43
70,0.020_1.0_0.030_3.0,Long,1866.889872,12429.478680,557.771288,4.505957,88,4660.265193,45,-2793.375321,43
71,0.020_1.0_0.030_4.0,Long,1866.889872,12429.478680,557.771288,4.505957,88,4660.265193,45,-2793.375321,43
95,0.025_1.0_0.030_4.0,Long,1291.471247,9692.741311,419.568928,3.997232,35,2064.145296,19,-772.674049,16
94,0.025_1.0_0.030_3.0,Long,1291.471247,9692.741311,419.568928,3.997232,35,2064.145296,19,-772.674049,16
93,0.025_1.0_0.030_2.0,Long,1291.471247,9692.741311,419.568928,3.997232,35,2064.145296,19,-772.674049,16
92,0.025_1.0_0.030_1.0,Long,1291.471247,9692.741311,419.568928,3.997232,35,2064.145296,19,-772.674049,16
63,0.020_1.0_0.020_4.0,Long,1210.357242,8489.252409,494.226240,4.277257,92,3325.652265,39,-2115.295022,53
62,0.020_1.0_0.020_3.0,Long,1210.357242,8489.252409,494.226240,4.277257,92,3325.652265,39,-2115.295022,53
61,0.020_1.0_0.020_2.0,Long,1210.357242,8489.252409,494.226240,4.277257,92,3325.652265,39,-2115.295022,53
60,0.020_1.0_0.020_1.0,Long,1210.357242,8489.252409,494.226240,4.277257,92,3325.652265,39,-2115.295022,53
87,0.025_1.0_0.020_4.0,Long,707.908102,8400.614462,261.247315,2.528058,36,1399.675417,17,-691.767315,19
86,0.025_1.0_0.020_3.0,Long,707.908102,8400.614462,261.247315,2.528058,36,1399.675417,17,-691.767315,19
85,0.025_1.0_0.020_2.0,Long,707.908102,8400.614462,261.247315,2.528058,36,1399.675417,17,-691.767315,19
84,0.025_1.0_0.020_1.0,Long,707.908102,8400.614462,261.247315,2.528058,36,1399.675417,17,-691.767315,19

In [8]:
df_dict['JumpTrailing_NoFilter_None'][1][['Test_ID', 'Type', 'Profit','Profit_With_Drawdown', 'Max_Drawdown', 'Max_Drawdown_Pct',
       'Trade_Count', 'Winning_Profit', 'Winning_Count', 'Losing_Profit',
       'Losing_Count']].sort_values(by='Profit_With_Drawdown',ascending=False).head(20)

,Test_ID,Type,Profit,Profit_With_Drawdown,Max_Drawdown,Max_Drawdown_Pct,Trade_Count,Winning_Profit,Winning_Count,Losing_Profit,Losing_Count
92,0.025_1.0_0.030_1.0,Long,1145.293060,3573.387533,1096.733585,9.615188,146,5904.528569,54,-4759.235509,92
68,0.020_1.0_0.030_1.0,Long,1085.653662,3010.805546,1239.159435,10.817573,272,10309.844304,110,-9224.190642,162
116,0.030_1.0_0.030_1.0,Long,498.154134,2892.207643,569.574020,5.167203,83,3087.952027,33,-2589.797894,50
106,0.030_1.0_0.015_3.0,Long,592.228543,2888.090944,673.359144,6.151765,91,2443.324125,16,-1851.095582,75
107,0.030_1.0_0.015_4.0,Long,418.011705,2055.892600,669.225365,6.099711,89,2212.516919,15,-1794.505213,74
63,0.020_1.0_0.020_4.0,Long,934.643437,2024.455648,1745.384417,13.850293,254,7650.349006,33,-6715.705569,221
105,0.030_1.0_0.015_2.0,Long,320.239791,2017.480116,495.937315,4.761977,92,2072.840111,23,-1752.600320,69
66,0.020_1.0_0.025_3.0,Long,811.771300,1826.522826,1663.310132,13.333060,238,7954.862430,37,-7143.091130,201
112,0.030_1.0_0.025_1.0,Long,258.284635,1523.577406,532.331045,5.085753,86,2496.824745,31,-2238.540110,55
61,0.020_1.0_0.020_2.0,Long,580.664419,1464.891628,1381.514908,11.891619,294,8158.920457,60,-7578.256038,234
113,0.030_1.0_0.025_2.0,Long,317.922999,1427.615404,727.972569,6.680854,82,2587.222392,20,-2269.299393,62
83,0.025_1.0_0.015_4.0,Long,652.245040,1400.985125,1615.109454,13.966852,159,4098.513638,21,-3446.268598,138
64,0.020_1.0_0.025_1.0,Long,511.782350,1348.052458,1251.975401,11.389372,300,8665.021351,120,-8153.239000,179
67,0.020_1.0_0.025_4.0,Long,673.732651,1298.684367,1875.998289,15.563427,221,7362.566410,27,-6688.833759,194
93,0.025_1.0_0.030_2.0,Long,556.299517,1204.394807,1605.144021,13.856740,140,5276.112062,30,-4719.812545,110
86,0.025_1.0_0.020_3.0,Long,554.107073,975.048249,1993.582214,17.048605,153,4274.533667,23,-3720.426594,130
65,0.020_1.0_0.025_2.0,Long,385.258500,974.853095,1375.132271,11.855894,263,8109.204749,60,-7723.946249,203
69,0.020_1.0_0.030_2.0,Long,312.387575,693.665483,1527.994843,13.510298,241,8293.213984,51,-7980.826410,190
117,0.030_1.0_0.030_2.0,Long,198.902101,615.562577,1094.771960,9.693674,80,2809.517149,21,-2610.615048,59
71,0.020_1.0_0.030_4.0,Long,258.872911,447.996966,2100.775190,17.335357,193,6817.755467,25,-6558.882557,168

In [9]:
df_dict['JumpTrailing_Filter_Greater'][1][['Test_ID', 'Type', 'Profit','Profit_With_Drawdown', 'Max_Drawdown', 'Max_Drawdown_Pct',
       'Trade_Count', 'Winning_Profit', 'Winning_Count', 'Losing_Profit',
       'Losing_Count']].sort_values(by='Profit_With_Drawdown',ascending=False).head(20)

,Test_ID,Type,Profit,Profit_With_Drawdown,Max_Drawdown,Max_Drawdown_Pct,Trade_Count,Winning_Profit,Winning_Count,Losing_Profit,Losing_Count
106,0.030_1.0_0.015_3.0,Long,222.761161,1153.068074,615.969294,5.795698,52,1296.081342,10,-1073.320182,42
105,0.030_1.0_0.015_2.0,Long,93.862933,670.017371,431.193005,4.202709,52,1127.485938,13,-1033.623005,39
107,0.030_1.0_0.015_4.0,Long,67.625340,332.655030,647.364618,6.098691,50,1081.135521,10,-1013.510182,40
113,0.030_1.0_0.025_2.0,Long,61.875430,283.942102,692.921621,6.537470,48,1391.275051,12,-1329.399621,36
63,0.020_1.0_0.020_4.0,Long,9.196413,26.176266,1126.462225,10.539792,134,3277.465809,17,-3268.269396,117
112,0.030_1.0_0.025_1.0,Long,3.234796,16.660581,600.443790,5.824760,50,1330.544317,18,-1327.309521,32
61,0.020_1.0_0.020_2.0,Long,-59.395658,-187.184433,1045.835040,9.519327,141,3343.631171,26,-3403.026829,115
92,0.025_1.0_0.030_1.0,Long,-64.126730,-221.647033,927.251209,8.679574,81,2634.138070,27,-2698.264800,54
70,0.020_1.0_0.030_3.0,Long,-95.888581,-254.841665,1207.476396,11.288019,118,3819.398516,18,-3915.287098,100
108,0.030_1.0_0.020_1.0,Long,-52.254869,-256.360044,630.187535,6.115017,53,1182.558032,18,-1234.812901,35
116,0.030_1.0_0.030_1.0,Long,-68.320170,-298.609656,715.283204,6.863827,48,1531.894799,17,-1600.214969,31
82,0.025_1.0_0.015_3.0,Long,-100.864141,-345.661912,933.442695,8.754000,86,1693.677797,11,-1794.541938,75
71,0.020_1.0_0.030_4.0,Long,-203.139391,-460.859751,1411.925397,13.223506,114,3663.297540,15,-3866.436931,99
110,0.030_1.0_0.020_3.0,Long,-122.874103,-473.695493,824.662939,7.781841,50,1077.258753,10,-1200.132856,40
111,0.030_1.0_0.020_4.0,Long,-133.900123,-481.147994,880.944729,8.348790,47,961.144911,7,-1095.045034,40
58,0.020_1.0_0.015_3.0,Long,-155.038320,-484.436989,1045.620552,9.601145,153,2841.812859,22,-2996.851179,131
68,0.020_1.0_0.030_1.0,Long,-225.138293,-607.337666,1219.660200,11.120912,134,4106.768700,50,-4331.906992,84
114,0.030_1.0_0.025_3.0,Long,-262.391760,-847.806397,976.210017,9.284847,47,1035.600184,8,-1297.991943,39
84,0.025_1.0_0.020_1.0,Long,-254.256707,-910.697804,866.397915,8.375667,88,1721.367807,27,-1975.624514,61
66,0.020_1.0_0.025_3.0,Long,-418.777463,-977.381322,1352.781553,12.854066,128,3241.157449,19,-3659.934911,109

In [10]:
df_dict['JumpTrailing_Filter_Less'][1][['Test_ID', 'Type', 'Profit','Profit_With_Drawdown', 'Max_Drawdown', 'Max_Drawdown_Pct',
       'Trade_Count', 'Winning_Profit', 'Winning_Count', 'Losing_Profit',
       'Losing_Count']].sort_values(by='Profit_With_Drawdown',ascending=False).head(20)

,Test_ID,Type,Profit,Profit_With_Drawdown,Max_Drawdown,Max_Drawdown_Pct,Trade_Count,Winning_Profit,Winning_Count,Losing_Profit,Losing_Count
66,0.020_1.0_0.025_3.0,Long,3703.638629,17387.862796,935.443364,6.390041,76,5965.739778,16,-2262.101149,60
64,0.020_1.0_0.025_1.0,Long,1665.268483,17287.619524,344.660422,2.889817,89,4006.896897,43,-2341.628413,46
83,0.025_1.0_0.015_4.0,Long,1805.447822,16460.331455,358.291835,3.290543,34,2484.039656,7,-678.591835,27
63,0.020_1.0_0.020_4.0,Long,3366.875805,16160.769324,880.391972,6.250091,77,5416.648768,15,-2049.772963,62
86,0.025_1.0_0.020_3.0,Long,2046.269991,15653.198006,430.361835,3.921761,33,2714.845226,9,-668.575235,24
54,0.020_1.0_0.010_3.0,Long,1467.749927,13959.950326,349.870000,3.154202,95,2886.300315,19,-1418.550388,76
62,0.020_1.0_0.020_3.0,Long,2522.208806,13328.140429,751.285796,5.677181,83,4583.686706,18,-2061.477900,65
90,0.025_1.0_0.025_3.0,Long,2021.424628,12758.820092,516.087116,4.753005,32,2830.638862,8,-809.214234,24
55,0.020_1.0_0.010_4.0,Long,1314.930407,12493.204307,350.580000,3.157550,94,2707.716744,17,-1392.786337,77
68,0.020_1.0_0.030_1.0,Long,1866.889872,12429.478680,557.771288,4.505957,88,4660.265193,45,-2793.375321,43
87,0.025_1.0_0.020_4.0,Long,1603.924001,12254.806588,425.197428,3.926437,33,2267.313101,8,-663.389100,25
65,0.020_1.0_0.025_2.0,Long,2124.401187,12188.523641,668.945692,5.228856,84,4495.211103,25,-2370.809916,59
67,0.020_1.0_0.025_4.0,Long,2892.233557,12046.689277,1000.642807,7.202560,75,5113.310991,13,-2221.077434,62
106,0.030_1.0_0.015_3.0,Long,648.862084,12040.598062,168.387681,1.616686,18,982.845738,4,-333.983654,14
107,0.030_1.0_0.015_4.0,Long,645.549701,11955.433923,169.267681,1.619890,18,987.160064,3,-341.610363,15
61,0.020_1.0_0.020_2.0,Long,1897.063902,11755.623391,604.243102,4.841250,87,4067.196455,26,-2170.132552,61
85,0.025_1.0_0.020_2.0,Long,1359.541135,11451.293286,377.074575,3.561714,34,2033.405916,10,-673.864781,24
69,0.020_1.0_0.030_2.0,Long,2560.624426,11280.516070,917.866322,6.809860,80,5076.022530,22,-2515.398103,58
93,0.025_1.0_0.030_2.0,Long,1905.699163,10800.040675,580.868616,5.293589,33,2752.203240,11,-846.504077,22
59,0.020_1.0_0.015_4.0,Long,1804.695908,10293.373562,655.372128,5.259780,86,3748.036171,13,-1943.340263,73

In [13]:
df = df_dict['JumpTrailing_Filter_Less'][0]
df[df['Test_ID'] == '0.020_1.0_0.025_3.0']

,Test_ID,Type,Ticket,Symbol_open,OpenPrice,OpenTime,fast_MA,fast_MA_prev,fast_EMA_diff,body,...,AD,MFI,AO,AC,DeMarker,Alligator,Symbol_close,ClosePrice,Profit,CloseTime
20986,0.020_1.0_0.025_3.0,Long,1,ETHUSD,2262.0,2024.01.03 14:02:51,1.036668,1.040444,-0.003777,25.7,...,0.908055,22.268210,-25.749706,-14.748882,0.172043,1.047760,ETHUSD,2206.4,-57.860000,2024.01.03 14:08:42
20987,0.020_1.0_0.025_3.0,Long,2,ETHUSD,2293.4,2024.01.09 23:13:43,0.985443,0.986530,-0.001087,5.8,...,11.393896,48.452831,-4.350882,-2.864647,0.324272,0.988533,ETHUSD,2542.8,241.571289,2024.01.12 23:09:58
20988,0.020_1.0_0.025_3.0,Long,3,ETHUSD,2713.0,2024.02.14 10:58:34,0.976553,0.975701,0.000853,5.3,...,33.490230,86.225548,17.102941,2.158412,0.880460,0.970546,ETHUSD,3280.4,552.967385,2024.02.28 19:31:43
20989,0.020_1.0_0.025_3.0,Long,4,ETHUSD,3650.5,2024.03.06 06:56:24,0.970562,0.968397,0.002165,27.9,...,99.148605,56.761660,31.031176,7.596529,0.537372,0.969864,ETHUSD,3815.7,158.841605,2024.03.14 20:46:34
20990,0.020_1.0_0.025_3.0,Long,5,ETHUSD,3540.9,2024.04.08 10:14:57,0.971700,0.969791,0.001908,5.1,...,146.304316,69.657384,13.858529,10.233294,0.875691,0.965929,ETHUSD,3540.7,-5.696720,2024.04.09 16:39:54
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21058,0.020_1.0_0.025_3.0,Long,73,ETHUSD,2104.6,2026.03.31 18:41:34,0.978471,0.978090,0.000381,2.1,...,698.605078,61.557764,14.806176,-1.184353,0.501520,0.973467,ETHUSD,2102.5,-8.186555,2026.04.02 03:30:44
21059,0.020_1.0_0.025_3.0,Long,74,ETHUSD,2155.9,2026.04.07 23:12:53,0.976310,0.975447,0.000863,0.1,...,681.701304,54.969576,25.637647,7.543882,0.815789,0.967829,ETHUSD,2155.8,-5.574666,2026.04.09 16:28:33
21060,0.020_1.0_0.025_3.0,Long,75,ETHUSD,2308.3,2026.04.11 20:36:53,0.977736,0.977217,0.000519,2.0,...,639.483479,53.771376,13.473824,-0.175765,0.858974,0.971454,ETHUSD,2270.5,-54.950000,2026.04.12 03:33:49
21061,0.020_1.0_0.025_3.0,Long,76,ETHUSD,2304.6,2026.04.14 00:14:43,0.977340,0.976682,0.000658,1.3,...,642.492522,68.498575,25.938529,-2.357529,0.902896,0.965058,ETHUSD,2304.0,-3.980000,2026.04.14 21:25:27
21062,0.020_1.0_0.025_3.0,NaN,-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ETHUSD,-1.0,-1.000000,2026.04.29 22:00:00